### ISSUE TITLE
Why I can't disable it

### ISSUE THREAD

**Issue by sanstale6** [matteozappia/DynamicCowTS#7]
I enable it in my ipad5(16.6.1),but when I clicked disable there was nothing happened after respring

And the dynamic island can't be used,it's only a black rectangle in the screen

Upon enabling Dynamic Island, I observed that the ArtworkDeviceSubType value is 2796, whereas it becomes 2556 upon disablement. However, neither of these values seems to affect the disappearance of the dynamic island. (I am unsure of the relevance of these values in addressing the issue at hand.)

It appears that I may have discerned the underlying reason. It seems that the DynamicCow application has, somewhat inexplicably, recorded the ArtworkDeviceSubType of the original device incorrectly.(Now I change it to 2749 to disable the dynamic island,but I don't know what will happen)

**Comment by Pierhincho** [comment]
Did you ever fix it?

**Comment by sanstale6** [comment]
> Did you ever fix it?

I has fixed it

**Comment by tanjj1228** [comment]
i met the same problem, how did you solve it?

**Comment by tanjj1228** [comment]
> > Did you ever fix it?
> 
> I has fixed it

i met the same problem, how did you solve it?

**Comment by sanstale6** [comment]
> > > Did you ever fix it?
> > 
> > 
> > I has fixed it
> 
> i met the same problem, how did you solve it?

The principle of enabling DynamicCow is to modify the value of ArtworkDeviceSubType. This value is located in `/var/containers/Shared/SystemGroup/systemgroup.com.apple.mobilegestaltcache/Library/Caches/com.apple.MobileGestalt.plist`. After opening this file, open Root, CacheExtra, oPeik/9e8lQWMszEjbPzng in sequence, and find ArtworkDeviceSubType. Then you need to check the resolution of your iOS device. The second number of the resolution is the value of ArtworkDeviceSubType. For example, the resolution of my iPad 5 is 2048×1536, so the ArtworkDeviceSubType should be 1536. Change the ArtworkDeviceSubType value after enabling DynamicCow (usually 2796, 2556) to this value, save it, and then respring.

**Comment by sanstale6** [comment]
> > > Did you ever fix it?
> > 
> > 
> > I has fixed it
> 
> i met the same problem, how did you solve it?

开启DynamicCow的原理是修改ArtworkDeviceSubType的值，这个值位于/var/containers/Shared/SystemGroup/systemgroup.com.apple.mobilegestaltcache/Library/Caches/com.apple.MobileGestalt.plist中。打开这个文件后以此打开Root,CacheExtra,oPeik/9e8lQWMszEjbPzng,在其中找到ArtworkDeviceSubType    然后你需要查询你的ios设备的分辨率，分辨率的第二个数值就是ArtworkDeviceSubType的值，如我的ipad5的分辨率为2048×1536，那么ArtworkDeviceSubType就应为1536，把开启DynamicCow后的ArtworkDeviceSubType值(一般为2796,2556)更改为这个值，保存后respring就行了
